name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    # ✅ NEW STEP (required workaround)
    - name: Dummy upload artifact step (to satisfy GitHub dependency)
      uses: actions/upload-artifact@v3
      with:
        name: dummy
        path: ./site/index.html

    - name: Upload site files
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2

